### ISSUE TITLE
Combat tracker not showing hidden creatures when 

### ISSUE THREAD

**Issue by ariakas2008** [casualchameleon/MusicAssist#1]
there is an issue with the combat tracker: hidden creatures are no more showed in it.
I am 99% sure it's last update's fault, since I tried with just Music assist enabled and I also tried with the previous Music assist version and I can reproduce the issue with the former while it doesn't happen in the latter.
Core foundry 0.6.6, D&D 0.96, Module list (but remember this happens even with **only** Music Assist enabled)
about-time--v0.1.53;
actually-private-rolls--v0.2;
adventuremusic--v1.1.0;
arms-reach--v1.1.1;
babele--v1.19;
betternpcsheet5e--v0.8.3;
betterrolls5e--v1.1.11;
calendar-weather--v3.0.4;
combat-carousel--v0.1;
combat-utility-belt--v1.2.2;
custom-css--v1.1.2;
cycle-token-stack--v0.5.4;
deselection--v1.4.4;
df-settings-clarity--v1.1;
dice-so-nice--v2.0.4;
dice-calculator--v0.6.0;
FoundryVTT-dnd5e-it--v0.25;
dragupload--v1.4.1;
foundry-drmapzo-free--v0.15.0;
dynamiceffects--v0.5.101;
foundry_community_macros--v0.25;
fxmaster--v0.6.0;
gm-notes--v0.2;
illandril-sheet5e-lockdown--v2.0.0;
inlinewebviewer--v1.4.1;
inventory-plus--v0.2;
FoundryVTT - it-IT--v0.12;
itemcollection--v1.3.15;
item-delete-check--v1.0.3;
jaamod--v0.2;
laptop-fix--v0.0.8;
colorsettings--v2.5.0;
lootsheetnpc5e--v2.1.1;
maestro--v0.7.1;
magicitems--v1.19;
mess--v0.11.2;
michaelghelfi--v1.0;
mountup--v3.0.1;
multilevel-tokens--v1.2.0;
music-assist-- SEE ABOVE
permission_viewer--v0.7;
pick-up-stix--v0.10.0;
pings--v1.2.9;
plutonium--v1.10.2;
polyglot--v1.1.2;
quicksceneview--v0.0.2;
returntosetup--v1.0.3;
searchanywhere--v2.0.4;
ShowDragDistance--v2.1.8;
foundryvtt-show-notes--v0.2;
simple-dice-roller--v0.2.2;
switch-to-chat--v0.1.1;
furnace--v2.2;
tidy5e-sheet--v0.2.24;
tidy-ui_game-settings--v0.1.18;
token-action-hud--v0.7.17;
token-auras--v1.5;
token-hud-wildcard--v1.0.0;
tokenmagic--v0.4.3;
workshop-ammo-swapper--v0.1.2;

**Comment by casualchameleon** [comment]
Hi @ariakas2008, this has been fixed now and a new release has been created which can be found here: https://github.com/casualchameleon/MusicAssist/releases/tag/v0.2.1.

I'll leave the issue open for now.

**Comment by ariakas2008** [comment]
Seems solved, thank you very much!
